Grooscript offer two annotations to add in your groovy code.

=== GsNative

You can annotate groovy methods with @GsNative. The javascript code of that method will be the code inside comment,
between `/&#42;` and `&#42;/`, that fragment has to be after `{` method start. I use a lot this feature to insert
javascript code in the groovy code. So when I run the code in groovy nothing happens (tests pass), but the
javascript code runs in converted code.

[source,groovy]
--
import org.grooscript.asts.GsNative

class Numbers {

    @GsNative
    def getFive() {/*
        $('something').andMoreJsCode();
        return 5;
    */}

    def getSix() {
        6
    }
}
--

This is a very useful feature, even you can put javascript code in a block comment and groovy code after.

[source,groovy]
--
include::../src/test/resources/asts/advancedNative.groovy[tags=mixNative,indent=0]
--

=== GsNotConvert

You can annotate your classes and methods with @GsNotConvert and that code will not be converted to javascript.

[source,groovy]
--
import org.grooscript.asts.GsNotConvert

@GsNotConvert
class ClassNotConvert {
    def a
}

class A {
    @GsNotConvert
    def methodNotConvert() {
        println 'No!'
    }

    def hello() {
        println 'Hello!'
    }
}
--