= link:{index-file}[Grooscript] documentation

*Groovy to javascript transpiler*

== Introduction

include::introduction.adoc[]

== Getting started

include::getting_started.adoc[]

== Conversion

For convert groovy code to javascript, that groovy code is compiled. Then javascript code is generated
visiting generated AST tree. You can try link:conversions.html[online] conversions at grooscript site.

=== Options

To help in conversion process, you can set some conversion options. To set conversion options:

[source,groovy]
--
//Set a conversion property
GrooScript.setConversionProperty('recursive', true)
GrooScript.setConversionProperty('customization', {
    ast(CompileStatic)
})
//Applied to next conversions
--

include::conversion_options.adoc[]

=== General support

include::general_support.adoc[]

=== Java support [Jorge]

include::java_support.adoc[]

=== Groovy support

Groovy specific features supported...

== Converted code

How to work with converted code in js world...

== PhantomJs tests

include::phantomjstest.adoc[]

== Annotations

include::annotations.adoc[]

== Helper Tools

include::tools.adoc[]

== Tricks

== Tools

=== Gradle plugin

=== Grails plugin

=== Npm package

== Guides

== Acknowledgements