= link:{index-file}[Grooscript] documentation

*Groovy to javascript transpiler*

== Introduction

include::introduction.adoc[]

== Requirements

include::requirements.adoc[]

== Getting started

include::getting_started.adoc[]

== Conversion

For convert groovy code to javascript, that groovy code is compiled. Then javascript code is generated
visiting generated AST tree. You can try link:conversions.html[online] conversions at grooscript site. In the
source of the project you can take a look at all the groovy code that is converted to javascript in tests,
you have full scope of all supported features in a lot of
https://github.com/chiquitinxx/grooscript/tree/master/src/test/resources[groovy scripts]

You usually will convert files with groovy code to a destination folder or js file. To be dynamic and automatize
conversion process I strongly recommend to use https://github.com/chiquitinxx/grooscript-gradle-plugin[grooscript gradle plugin].
You can activate a daemon to automatically convert groovy code when files are modified.

=== Options

To help in conversion process, you can set some conversion options. To set conversion options:

[source,groovy]
--
//Set a conversion property
GrooScript.setConversionProperty('recursive', true)
GrooScript.setConversionProperty('customization', {
    ast(CompileStatic)
})
//Applied to next conversions
--

include::conversion_options.adoc[]

=== General support

include::general_support.adoc[]

=== Java support

include::java_support.adoc[]

=== Groovy support

include::groovy_support.adoc[]

== Converted code

include::converted_code.adoc[]

== PhantomJs tests

include::phantomjstest.adoc[]

== Annotations

include::annotations.adoc[]

== Helper Tools

include::tools.adoc[]

== Tricks [Jorge]

include::tricks.adoc[]

== Tools

    TODO

=== Gradle plugin

    TODO

=== Grails plugin

    TODO

=== Npm package

    TODO

== Guides

    TODO

== Acknowledgements

include::acknowledgements.adoc[]