In general groovy features are supported, except advanced metaprogramming techniques and AST's applied in phases
after semantic analysis. `as` is supported only at specific situations. Let's see examples of some conversions.

==== GStrings

[source,groovy]
--
include::../src/test/resources/advanced/StringSecrets.groovy[tags=strings,indent=0]
--

==== Default constructor, optional parameters, pointer methods, multiple assignment

[source,groovy]
--
include::../src/test/resources/doc/LittleFeatures.groovy[tags=features,indent=0]
--

==== Operators

`&lt;=&gt;`, `.@`, `*.`, `in`, `is`, `?.` and `?:` are supported.

[source,groovy]
--
include::../src/test/resources/doc/Operators.groovy[tags=operators,indent=0]
--

Also you can overload this operators in your classes:

.Overload operators
|===
|operator |function

|a + b
|a.plus(b)

|a - b
|a.minus(b)

|a * b
|a.multiply(b)

|a ** b
|a.power(b)

|a / b
|a.div(b)

|a % b
|a.mod(b)

|a << b
|a.leftShift(b)

|a >> b
|a.rightShift(b)
|===

==== Regular expressions

Javascript support regular expressions, so I use it with groovy style. Not much tests on this, try it before .

[source,groovy]
--
include::../src/test/resources/regularExpressionsBegin.groovy[tags=regs,indent=0]
--

==== Lists, ranges, maps ans sets

A lot of lists and map functions are implemented, so the support is very good.

[source,groovy]
--
include::../src/test/resources/listFunctions.groovy[tags=lists,indent=0]
--

Ranges with negative numbers are not supported.

==== Groovy truth

[source,groovy]
--
include::../src/test/resources/doc/Truth.groovy[tags=truth,indent=0]
--

Also, you can customize groovy truth of your classes

[source,groovy]
--
include::../src/test/resources/contribution/GuillaumeCustomizeTruth.groovy[tags=customize,indent=0]
--

==== Expando class

JavaScript object is similar to Expando object

    TODO

==== Numbers

Numbers types are ignored, in conversion we are working with javascript numbers.

    TODO

==== Categories and Mixing

Categories are suported with annotation and with the ´use´ keyword. Mixins also supported but we moved to
better support traits.

    TODO

==== Switch

Has basic support, can't assign variables inside.
    TODO

==== Closures

Closures are converted to javascript functions. call, curry, rcurry, ncurry, leftShift are supported. If you
set delegate of a closure, it will be used.

    TODO

==== GroovyBeans

Support getter and setters as groovy does. Supporting getProperty, setProperty, methodMissing, propertyMissing.
Added invokeMethod but don't intercept calls.

    TODO

==== Metaprogramming

Can add/modify properties and methods in execution time. Some problems with primitive types as Integer or String.
Can use getProperties() and getMethods() to get names. Can add properties/methods to classes.
Just working on dynamic features needed, never a full groovy metaClass, metaInfo, ... support.

    TODO

==== AST's

Support to @Mixin, @Category and @Delegate. Annotations in semantic phase, will be applied and converted, is same phase
that grooscript use.

    TODO

==== Traits

Good support, in compile and runtime. Don't support SAM coercion and super.

    TODO
