In general groovy features are supported, except advanced metaprogramming techniques and AST's applied in phases
after semantic analysis. `as` is supported only at specific situations. Owner is totally ignored.

Let's see examples of some conversions.

==== GStrings

[source,groovy]
--
include::../src/test/resources/advanced/StringSecrets.groovy[tags=strings,indent=0]
--

==== Default constructor, optional parameters, pointer methods, multiple assignment

[source,groovy]
--
include::../src/test/resources/doc/LittleFeatures.groovy[tags=features,indent=0]
--

==== Operators

`&lt;=&gt;`, `.@`, `*.`, `...`, `in`, `is`, `?.` and `?:` are supported.

[source,groovy]
--
include::../src/test/resources/doc/Operators.groovy[tags=operators,indent=0]
--

`*` is not supported in *list, to divide a list in parameters for a function / method.

Also you can overload this operators in your classes:

.Overload operators
|===
|operator |function

|a + b
|a.plus(b)

|a - b
|a.minus(b)

|a * b
|a.multiply(b)

|a ** b
|a.power(b)

|a / b
|a.div(b)

|a % b
|a.mod(b)

|a << b
|a.leftShift(b)

|a >> b
|a.rightShift(b)
|===

==== Regular expressions

Javascript support regular expressions, so I use it with groovy style. Not much tests on this, try it before .

[source,groovy]
--
include::../src/test/resources/regularExpressionsBegin.groovy[tags=regs,indent=0]
--

==== Lists, ranges, maps ans sets

A lot of lists and map functions are implemented, so the support is very good. The `*` operator to get lists is
available too.

[source,groovy]
--
include::../src/test/resources/listFunctions.groovy[tags=lists,indent=0]
--

Ranges with negative numbers are not supported.

==== Groovy truth

[source,groovy]
--
include::../src/test/resources/doc/Truth.groovy[tags=truth,indent=0]
--

Also, you can customize groovy truth of your classes

[source,groovy]
--
include::../src/test/resources/contribution/GuillaumeCustomizeTruth.groovy[tags=customize,indent=0]
--

==== Expando class

JavaScript object is similar to Expando object, and is supported

[source,groovy]
--
include::../src/test/resources/advanced/ExpandoWorld.groovy[tags=mark,indent=0]
--

==== Numbers

Numbers types are ignored, in conversion we are working with javascript numbers. Math library is compatible with
javascript, and you can use it.

[source,groovy]
--
include::../src/test/resources/arithmetic.groovy[tags=mark,indent=0]
--

==== Categories and Mixins

Categories are suported with annotation and with the ´use´ keyword. Support on categories and mixins is not
very great, you can expect good support in categories, but not in mixins cause deprecated.

[source,groovy]
--
include::../src/test/resources/classes/MoreCategories.groovy[tags=mark,indent=0]
--

==== Switch

Groovy features are not supported, can't assign variables inside, not comparing with lists, sets, classes,
regular expressions, ... Just a basic switch.

[source,groovy]
--
include::../src/test/resources/contribution/Anonymous1.groovy[tags=mark,indent=0]
--

==== Closures

Closures are converted to javascript functions. call, curry, rcurry, ncurry, leftShift are supported. If you
set delegate of a closure, it will be used. dehydrate and rehydrate are not supported. Support closures
as last argument in methods, and closure composition.

[source,groovy]
--
include::../src/test/resources/contribution/GuillaumeClosuresComposition.groovy[tags=mark,indent=0]
//
include::../src/test/resources/contribution/GuillaumeTrailingClosure.groovy[tags=mark,indent=0]
--

==== GroovyBeans

Support getter and setters as groovy does, named parameters in the default constructor

[source,groovy]
--
include::../src/test/resources/doc/Beans.groovy[tags=mark,indent=0]
--

==== Metaprogramming

Can add/modify properties and methods in execution time. Some problems with primitive types as Integer or String.
Can use getProperties() and getMethods() to get names. Can add properties/methods to classes.
Supporting getProperty, setProperty, methodMissing, propertyMissing.
Added invokeMethod but doesn't intercept calls.
Just working on dynamic features needed, never a full groovy metaClass, metaInfo, ... support.

[source,groovy]
--
include::../src/test/resources/doc/Metaprogramming.groovy[tags=mark,indent=0]
--

==== AST's

Support to @Mixin, @Category and @Delegate. Annotations in semantic phase, will be applied and converted, is phase
where grooscript converts compiled code.

==== Traits

Good support, in compile and runtime. Don't support SAM coercion and super.

[source,groovy]
--
include::../src/test/resources/traits/Inheritance.groovy[tags=mark,indent=0]
--

==== Module extensions

Not supported.