From version 1.1, you can generate http://requirejs.org/[Require.js] modules. Require.js is a javascript modules loader,
like a package manager in javascript. In javascript, there isn't package manager, so if your project grows you have to
start to think in a solution to manage all javascript files and dependencies. I have chosen Require.js because is a
mature utility, used by a lot of projects and compatible with other frameworks like Node.js.

=== Start with one javascript file

To convert a groovy file to require.js modules, you have to set one groovy file and a destination path. If you set any
classpath for the conversions, that classpath will be used to find groovy files.

[source,groovy]
--
import org.grooscript.GrooScript

GrooScript.setConversionProperty('classPath', 'src/main/groovy')
GrooScript.convertRequireJs('src/main/groovy/Initial.groovy', 'jsModules')
--

If you run this, a file `*jsModules/Initial.js*` will be generated. The source files has to be inside the classPath folder.

This conversion is clever, and if Initial.groovy use other source files, that files also will be converted to modules. A
file in `*src/main/groovy/util/Data.groovy*` will be converted to a require.js module in `*jsModules/util/Data.js*`. Also that
dependency will be added in `*Initial.js*` module.

Then, you don't have to take care about all the files and dependencies, each time that you convert `*Initial.groovy*`, all
groovy files will be converted to modules, and all dependencies will be include in that modules.

=== Using it

You have all that javascript modules, now you can use in your require.js application. You have to be sure that
you include `*grooscript.js*` in your require.js dependencies. All require.js modules that you have generated are converted
groovy code that needs `*grooscript.js*` to run.

This is an example require.js initial file:

[source,javascript]
--
requirejs.config({
    baseUrl: 'jsModules',
    paths: {
        lib: 'js/lib'
    }
});

requirejs(['lib/grooscript.min'], function() {
    requirejs(['Initial']);
});
--

And that's all, you don't have to worry about more groovy files, just add javascript dependencies in your project.

TIP: The grooscript gradle plugin has task to generate require.js modules, and listen for changes to speed up your development
experience.